<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--<OutputType>Exe</OutputType>-->
    <OutputType>WinExe</OutputType> <!--Без окна консоли-->
	<PublishAot>true</PublishAot>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SFML.Net" Version="2.6.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Monocraft-nerd-fonts-patched.ttc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="WinImage.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
